import Footer from '@/Components/Footer/Footer'
import Navbar from '@/Components/Navbar/Navbar'
import { Yellowtail } from 'next/font/google'
// import { store } from './store'
// import { Provider } from 'react-redux'

const yellowTail = Yellowtail({
    subsets: ['latin'],
    weight: '400',
    preload: true,
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function layout({ children }) {
    return (
        <section>
            {/* <Provider store={store}> */}
            {/* <Navbar /> */}
            {children}
            {/* <Footer /> */}
            {/* </Provider> */}
        </section>
    )
}
