import Footer from '@/Components/Footer/Footer'
import Navbar from '@/Components/Navbar/Navbar'
import './globals.scss'
import { Yellowtail } from 'next/font/google'
// import { store } from './store'
// import { Provider } from 'react-redux'

const yellowTail = Yellowtail({
  subsets: ['latin'],
  weight: '400',
  preload: true,
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={yellowTail.className}>
        {/* <Provider store={store}> */}
        <Navbar />
        {children}
        <Footer />
        {/* </Provider> */}
      </body>
    </html>
  )
}
